### PR TITLE
New feature: add eggNOG annotations

### PR DESCRIPTION
**Pull request by Zygnematophyce**
Hi @holmrenser,
New functionality for genenotebook . Now we can add the functional annotation results from new sequences with the tool [EggNOG-mapper 5](http://eggnog5.embl.de/#/app/home).

Overview of eggNOG in genenotebook:

eggNog_example

In this new pull request:

- New CLI command **genenotebook add eggnog <file.tsv>** to add eggnog-mapper annotations.
- New eggNOG collection in the database
   - with data reading and integration
- New 19 [EggNOG annotations fields](https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.7#annotations-file)
   - with a small description for most fields,
   - search for additional information using the APIs.
(Locally there are *Cross-Origin Request Blocked* errors that can occur.)
- Table design and item with scss.

Table of APIs used:

| items | api | protocol |
| --- | --- | --- |
|Gene Ontology | https://api.geneontology.org/api/bioentity/ | https |
|Enzyme Commission | https://rest.kegg.jp/list/ | https |
|KEGG ko | https://rest.kegg.jp/find/ko/ | https |
|KEGG pathway | https://rest.kegg.jp/list/ | https |
|KEGG reaction | https://rest.kegg.jp/find/reaction/ | https |
|KEGG rclass | https://rest.kegg.jp/find/rclass/ | https |
|KEGG BRITE | https://rest.kegg.jp/find/brite/ | https |
|BiGG reaction | http://bigg.ucsd.edu/api/v2/models/iND750/genes/YER091C | http |
|PFAMS | https://pfam.xfam.org/family/Meth_synt_1/desc | http |

I also added some sample data for testing.

[MMUCEDO_data_20_04_2022.zip](https://github.com/genenotebook/genenotebook/files/8539344/MMUCEDO_data_20_04_2022.zip)

- genome.fa (sequences)
- MMUCEDO_annot.gff3 (the annotation)
-  MMUCEDO_eggnog.tsv (eggNOG)

with the following commands it should work:

```bash
genenotebook add genome -n test tests/genome.fa -u admin -p admin
genenotebook add annotation -n test tests/MMUCEDO_annot.gff3 -u admin -p admin
genenotebook add eggnog tests/MMUCEDO_eggnog.tsv -u admin -p admin
```

The data does not really make sense but allows to test the different scenarios:
- MMUCEDO_000001: (some eggNOG fields)
- MMUCEDO_000002: (all eggNOG fields)
- MMUCEDO_000004: (only name and _id of eggNOG without other fields (rare))
- MMUCEDO_000005: (no information linking eggNOG and the gene)

### CODE REVIEW

**Comment by holmrenser** [comment]
Awesome! By what I can see now this looks really impressive. I would like to toy around a bit with it locally before merging it into the master branch, could you make this PR against the dev branch?

**Comment by Zygnematophyce** [comment]
I had tested, eggNOG seems to be broken on the dev branch. However, on the master branch everything seems to work.

**Comment by abretaud** [comment]
(FYI @Zygnematophyce is away this week)

**Comment by holmrenser** [comment]
Curious to see what has broken so I'm going to merge this. This is why there is a dev branch anyway :-)

**Comment by Zygnematophyce** [comment]
I simply rebuilt the *genes collection* and everything works fine. Definitely that was my mistake.

**Pull request merged**
